import type { Subscription } from './types'

export const initialSubscriptions: Subscription[] = [
  {
    id: '1',
    name: 'Netflix',
    category: 'Entertainment',
    amount: 649,
    currency: '₹',
    billingCycle: 'monthly',
    status: 'active',
    renewalDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    color: '#E50914',
    logo: 'N',
  },
  {
    id: '2',
    name: 'Spotify',
    category: 'Music',
    amount: 119,
    currency: '₹',
    billingCycle: 'monthly',
    status: 'active',
    renewalDate: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    color: '#1DB954',
    logo: 'S',
  },
  {
    id: '3',
    name: 'YouTube Premium',
    category: 'Entertainment',
    amount: 129,
    currency: '₹',
    billingCycle: 'monthly',
    status: 'unused',
    renewalDate: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    color: '#FF0000',
    logo: 'Y',
  },
  {
    id: '4',
    name: 'Amazon Prime',
    category: 'Entertainment',
    amount: 1499,
    currency: '₹',
    billingCycle: 'yearly',
    status: 'active',
    renewalDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    color: '#00A8E1',
    logo: 'P',
  },
  {
    id: '5',
    name: 'ChatGPT Plus',
    category: 'AI & Tools',
    amount: 480,
    currency: '₹',
    billingCycle: 'monthly',
    status: 'active',
    renewalDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    color: '#10A37F',
    logo: 'G',
  },
  {
    id: '6',
    name: 'Notion',
    category: 'Productivity',
    amount: 800,
    currency: '₹',
    billingCycle: 'monthly',
    status: 'paused',
    renewalDate: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    color: '#000000',
    logo: 'N',
  },
  {
    id: '7',
    name: 'Google One',
    category: 'Storage',
    amount: 129,
    currency: '₹',
    billingCycle: 'monthly',
    status: 'active',
    renewalDate: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    color: '#4285F4',
    logo: 'G',
  },
  {
    id: '8',
    name: 'Figma',
    category: 'Productivity',
    amount: 720,
    currency: '₹',
    billingCycle: 'monthly',
    status: 'unused',
    renewalDate: new Date(Date.now() + 32 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    color: '#F24E1E',
    logo: 'F',
  },
]
