/**
 * Mock data for Smart Capture system
 * Used for development and demonstration
 */

import type {
  SubscriptionCandidate,
  ConnectedAccount,
  IngestionEvent,
  NotificationLabEvent,
  IntegrationInfo,
  InboxCounts,
  SyncState,
} from './types'

// Mock connected accounts
export const mockConnectedAccounts: ConnectedAccount[] = [
  {
    id: 'acc_gmail_1',
    userId: 'user_1',
    provider: 'gmail',
    email: 'user@gmail.com',
    status: 'active',
    lastSync: new Date(Date.now() - 1000 * 60 * 15), // 15 mins ago
    webhookStatus: 'active',
    syncHealth: 'healthy',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30),
    updatedAt: new Date(Date.now() - 1000 * 60 * 15),
  },
]

// Mock subscription candidates
export const mockCandidates: SubscriptionCandidate[] = [
  {
    id: 'cand_1',
    userId: 'user_1',
    source: 'gmail',
    ingestionEventId: 'evt_1',
    providerName: 'Netflix',
    providerLogo: undefined,
    planName: 'Premium',
    amount: 649,
    currency: 'INR',
    billingCycle: 'monthly',
    confidenceScore: 95,
    confidenceLevel: 'high',
    status: 'new',
    evidenceSnippet: 'Your Netflix subscription has been renewed for Rs 649.00',
    evidenceDetails: [
      { type: 'sender', label: 'From', value: 'info@netflix.com', confidence: 100 },
      { type: 'amount', label: 'Amount', value: 'Rs 649.00', confidence: 98 },
      { type: 'subject', label: 'Subject', value: 'Your Netflix payment confirmation', confidence: 95 },
    ],
    tags: ['renewal'],
    renewalInfo: {
      nextRenewalDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 30),
      lastRenewalDate: new Date(),
      wasAutoRenewed: true,
    },
    detectedAt: new Date(Date.now() - 1000 * 60 * 30),
    createdAt: new Date(Date.now() - 1000 * 60 * 30),
    updatedAt: new Date(Date.now() - 1000 * 60 * 30),
  },
  {
    id: 'cand_2',
    userId: 'user_1',
    source: 'gmail',
    ingestionEventId: 'evt_2',
    providerName: 'Spotify',
    planName: 'Premium Individual',
    amount: 119,
    currency: 'INR',
    billingCycle: 'monthly',
    confidenceScore: 72,
    confidenceLevel: 'medium',
    status: 'review_needed',
    evidenceSnippet: 'Your Spotify Premium free trial ends tomorrow. You will be charged Rs 119.',
    evidenceDetails: [
      { type: 'sender', label: 'From', value: 'no-reply@spotify.com', confidence: 100 },
      { type: 'amount', label: 'Amount', value: 'Rs 119', confidence: 85 },
      { type: 'body', label: 'Trial ending', value: 'free trial ends tomorrow', confidence: 90 },
    ],
    tags: ['trial'],
    trialInfo: {
      endDate: new Date(Date.now() + 1000 * 60 * 60 * 24),
      daysRemaining: 1,
      autoRenews: true,
    },
    detectedAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
  },
  {
    id: 'cand_3',
    userId: 'user_1',
    source: 'notification_lab',
    ingestionEventId: 'evt_3',
    providerName: 'YouTube Premium',
    planName: 'Individual',
    amount: 129,
    currency: 'INR',
    billingCycle: 'monthly',
    confidenceScore: 88,
    confidenceLevel: 'high',
    status: 'new',
    evidenceSnippet: 'Payment successful for YouTube Premium - Rs 129',
    evidenceDetails: [
      { type: 'notification', label: 'App', value: 'Google Play', confidence: 100 },
      { type: 'amount', label: 'Amount', value: 'Rs 129', confidence: 95 },
    ],
    tags: ['renewal'],
    detectedAt: new Date(Date.now() - 1000 * 60 * 60),
    createdAt: new Date(Date.now() - 1000 * 60 * 60),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60),
  },
  {
    id: 'cand_4',
    userId: 'user_1',
    source: 'gmail',
    ingestionEventId: 'evt_4',
    providerName: 'Adobe Creative Cloud',
    planName: 'Photography Plan',
    amount: 999,
    currency: 'INR',
    billingCycle: 'monthly',
    confidenceScore: 45,
    confidenceLevel: 'low',
    status: 'review_needed',
    evidenceSnippet: 'Your Adobe invoice is ready. Amount: Rs 999.00',
    evidenceDetails: [
      { type: 'sender', label: 'From', value: 'mail@adobe.com', confidence: 100 },
      { type: 'amount', label: 'Amount', value: 'Rs 999.00', confidence: 90 },
    ],
    tags: [],
    possibleDuplicateId: 'sub_adobe_1',
    possibleDuplicateName: 'Adobe CC',
    detectedAt: new Date(Date.now() - 1000 * 60 * 60 * 4),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 4),
  },
  {
    id: 'cand_5',
    userId: 'user_1',
    source: 'gmail',
    ingestionEventId: 'evt_5',
    providerName: 'Amazon Prime',
    planName: 'Annual',
    amount: 1499,
    currency: 'INR',
    billingCycle: 'yearly',
    confidenceScore: 92,
    confidenceLevel: 'high',
    status: 'added',
    evidenceSnippet: 'Thank you for renewing Amazon Prime. Rs 1,499 charged.',
    evidenceDetails: [
      { type: 'sender', label: 'From', value: 'auto-confirm@amazon.in', confidence: 100 },
      { type: 'amount', label: 'Amount', value: 'Rs 1,499', confidence: 98 },
    ],
    tags: ['renewal'],
    renewalInfo: {
      nextRenewalDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 365),
      lastRenewalDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2),
      wasAutoRenewed: true,
    },
    detectedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2),
    reviewedAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
  },
  {
    id: 'cand_6',
    userId: 'user_1',
    source: 'outlook',
    ingestionEventId: 'evt_6',
    providerName: 'Microsoft 365',
    planName: 'Personal',
    amount: 4899,
    currency: 'INR',
    billingCycle: 'yearly',
    confidenceScore: 85,
    confidenceLevel: 'high',
    status: 'ignored',
    evidenceSnippet: 'Your Microsoft 365 subscription confirmation',
    evidenceDetails: [
      { type: 'sender', label: 'From', value: 'microsoft365@email.microsoft.com', confidence: 100 },
    ],
    tags: [],
    detectedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5),
    reviewedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4),
  },
  {
    id: 'cand_7',
    userId: 'user_1',
    source: 'gmail',
    ingestionEventId: 'evt_7',
    providerName: 'Unknown Service',
    amount: 299,
    currency: 'INR',
    billingCycle: 'unknown',
    confidenceScore: 0,
    confidenceLevel: 'low',
    status: 'error',
    evidenceSnippet: 'Payment received',
    evidenceDetails: [],
    tags: [],
    detectedAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
  },
]

// Mock notification lab events
export const mockNotificationLabEvents: NotificationLabEvent[] = [
  {
    id: 'lab_1',
    userId: 'user_1',
    appName: 'Google Play',
    title: 'Payment successful',
    body: 'Payment successful for YouTube Premium - Rs 129',
    timestamp: new Date(Date.now() - 1000 * 60 * 60),
    amount: 129,
    currency: 'INR',
    merchant: 'YouTube Premium',
    status: 'candidate_created',
    candidateId: 'cand_3',
    createdAt: new Date(Date.now() - 1000 * 60 * 60),
  },
  {
    id: 'lab_2',
    userId: 'user_1',
    appName: 'PhonePe',
    title: 'UPI Payment',
    body: 'Rs 499 paid to Hotstar',
    timestamp: new Date(Date.now() - 1000 * 60 * 30),
    amount: 499,
    currency: 'INR',
    merchant: 'Hotstar',
    status: 'processing',
    createdAt: new Date(Date.now() - 1000 * 60 * 30),
  },
]

// Mock integration info
export const mockIntegrations: IntegrationInfo[] = [
  {
    id: 'int_gmail',
    name: 'Gmail',
    description: 'Scan your Gmail for subscription receipts and renewal notices',
    icon: 'mail',
    isConnected: true,
    account: mockConnectedAccounts[0],
    lastSync: new Date(Date.now() - 1000 * 60 * 15),
    syncHealth: 'healthy',
    webhookStatus: 'active',
    canConnect: false,
    canReconnect: true,
    canRescan: true,
    canPause: true,
  },
  {
    id: 'int_outlook',
    name: 'Outlook',
    description: 'Connect your Outlook account to detect subscriptions',
    icon: 'mail',
    isConnected: false,
    canConnect: true,
    canReconnect: false,
    canRescan: false,
    canPause: false,
  },
  {
    id: 'int_automation',
    name: 'Automation Engine',
    description: 'Background processing for candidate detection and analysis',
    icon: 'cpu',
    isConnected: true,
    syncHealth: 'healthy',
    canConnect: false,
    canReconnect: false,
    canRescan: true,
    canPause: true,
  },
  {
    id: 'int_notification_lab',
    name: 'Notification Lab',
    description: 'Test notification parsing with simulated events',
    icon: 'flask',
    isConnected: true,
    syncHealth: 'healthy',
    canConnect: false,
    canReconnect: false,
    canRescan: false,
    canPause: false,
  },
]

// Mock sync state
export const mockSyncState: SyncState = {
  accountId: 'acc_gmail_1',
  provider: 'gmail',
  lastSyncStarted: new Date(Date.now() - 1000 * 60 * 16),
  lastSyncCompleted: new Date(Date.now() - 1000 * 60 * 15),
  messagesProcessed: 1247,
  candidatesCreated: 23,
  errorsCount: 2,
  consecutiveFailures: 0,
  isHealthy: true,
}

// Calculate inbox counts from mock candidates
export function getMockInboxCounts(): InboxCounts {
  return {
    new: mockCandidates.filter(c => c.status === 'new').length,
    reviewNeeded: mockCandidates.filter(c => c.status === 'review_needed').length,
    added: mockCandidates.filter(c => c.status === 'added').length,
    ignored: mockCandidates.filter(c => c.status === 'ignored').length,
    errors: mockCandidates.filter(c => c.status === 'error').length,
    total: mockCandidates.length,
  }
}

// Sample notification templates for the lab
export const notificationTemplates = [
  {
    id: 'tmpl_1',
    name: 'Netflix Renewal',
    appName: 'Netflix',
    title: 'Payment successful',
    body: 'Your Netflix subscription renewed for Rs 649',
    amount: 649,
    currency: 'INR',
  },
  {
    id: 'tmpl_2',
    name: 'Spotify Trial Ending',
    appName: 'Spotify',
    title: 'Trial ending soon',
    body: 'Spotify Premium free trial ends tomorrow',
    amount: 119,
    currency: 'INR',
  },
  {
    id: 'tmpl_3',
    name: 'YouTube Premium',
    appName: 'Google Play',
    title: 'Payment successful',
    body: 'Payment successful for YouTube Premium',
    amount: 129,
    currency: 'INR',
  },
  {
    id: 'tmpl_4',
    name: 'Subscription Cancelled',
    appName: 'PayPal',
    title: 'Subscription cancelled',
    body: 'Subscription cancelled successfully',
  },
]
